#!/bin/bash
DEST=""
for arg in "$@"; do
  [[ "$arg" =~ ^- ]] && continue
  DEST="$arg"
done
HOSTNAME="${DEST##*@}"
HOSTNAME="${HOSTNAME%%:*}"
HOSTNAME="${HOSTNAME:-unknown}"

LOGFILE="/sessions/${HOSTNAME}-$(date +%s).log"
SSH_CMD="/usr/bin/ssh $(printf '%q ' "$@")"
exec script -q -f -e -c "$SSH_CMD" "$LOGFILE"
